apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: local/frontend:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: '128Mi'
            cpu: '500m'
        ports:
        - containerPort: 80
        env:
        - name: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
          value: 'true'
        - name: Service__Ingredients__Host
          value: 'ingredients'
        - name: Service__Ingredients__Port
          value: '80'
        - name: Service__Ingredients__Protocol
          value: 'http'
        - name: Service__Orders__Host
          value: 'orders'
        - name: Service__Orders__Port
          value: '80'
        - name: Service__Orders__Protocol
          value: 'http'
        - name: Jaeger__ServiceName
          value: 'frontend'
        - name: Jaeger__Host
          value: 'jaeger-agent'
        - name: Jaeger__Port
          value: '6831'
          

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pizza
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    nodePort: 30001
